version: "3"
services:
  #  The Application
  app:
    container_name: app_me
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    env_file: '.env.prod'
    environment:
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "REDIS_PASSWORD=redispassword"
  prisma:
    container_name: prisma_app_me
    image: prismagraphql/prisma:1.17
    restart: always
    ports:
      - "4001:4001"

    environment:
      PRISMA_CONFIG: |
        port: 4001
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        #enable newversion data movle
        prototype: true
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo:27017
  mongo:
    container_name: mongo_app_me
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
  redis:
    container_name: redis_app_me
    image: 'redis:4-alpine'
    command: redis-server --requirepass redispassword
    ports:
      - '4003'
volumes:
  mongo: