const GET = 'GET_WORK'
const GET_SUCCESS = 'GET_WORK_SUCCESS'
const GET_FAILURE = 'GET_WORK_FAILURE'
const SET_WORK_ACTIVE = 'SET_WORK_ACTIVE'
const START_SUBSCRIBE_WORKS = 'START_SUBSCRIBE_WORKS'
const SUBSCRIBE_WORKS_IS_RUNNING = 'SUBSCRIBE_WORKS_IS_RUNNING'


const workTypes = {
    GET,
    GET_SUCCESS,
    GET_FAILURE,
    SET_WORK_ACTIVE,
    SUBSCRIBE_WORKS_IS_RUNNING,
    START_SUBSCRIBE_WORKS,
}

export {
    workTypes
}
