const GET = 'GET_WORK'
const GET_SUCCESS = 'GET_WORK_SUCCESS'
const GET_FAILURE = 'GET_WORK_FAILURE'
const SET_WORK_ACTIVE = 'SET_WORK_ACTIVE'
const START_SUBSCRIBE_WORKS = 'START_SUBSCRIBE_WORKS'
const SUBSRIBE_WORK_IS_RUNNING = 'SUBSRIBE_WORK_IS_RUNNING'
const STOP_SUBSCRIBE_WORKS = 'STOP_SUBSCRIBE_WORKS'

const workTypes = {
    GET,
    GET_SUCCESS,
    GET_FAILURE,
    SET_WORK_ACTIVE,
    SUBSRIBE_WORK_IS_RUNNING,
    START_SUBSCRIBE_WORKS,
    STOP_SUBSCRIBE_WORKS
}

export {
    workTypes
}
