export const GENERAL_GRAPH = 'GENERAL_GRAPH';
export const GENERAL_GRAPH_SUCCESS = 'GENERAL_GRAPH_SUCCESS';
export const GENERAL_GRAPH_FAILURE = 'GENERAL_GRAPH_FAILURE';

export const UPLOAD = 'UPLOAD';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';