const AUTH = 'AUTH'
const AUTH_SUCCESS = 'AUTH_SUCCESS'
const AUTH_FAILURE = 'AUTH_FAILURE'
const UNAUTHENTICATED = 'UNAUTHENTICATED'
const GET_USER_DATA = 'GET_USER_DATA'
const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE'
const LOGOUT = 'LOGOUT'

const userTypes = {
    AUTH,
    AUTH_SUCCESS,
    AUTH_FAILURE,
    UNAUTHENTICATED,
    GET_USER_DATA,
    GET_USER_DATA_SUCCESS,
    GET_USER_DATA_FAILURE,
    LOGOUT
}

export {
    userTypes
}