const GET = 'GET_POST'
const GET_SUCCESS = 'GET_POST_SUCCESS'
const GET_FAILURE = 'GET_POST_FAILURE'
const SET_POST_ACTIVE = 'SET_POST_ACTIVE'
const START_SUBSCRIBE_POSTS = 'START_SUBSCRIBE_POSTS'
const SUBSCRIBE_POSTS_IS_RUNNING = 'SUBSCRIBE_POSTS_IS_RUNNING'

const postTypes = {
    GET,
    GET_SUCCESS,
    GET_FAILURE,
    SET_POST_ACTIVE,
    SUBSCRIBE_POSTS_IS_RUNNING,
    START_SUBSCRIBE_POSTS,
}

export {
    postTypes
}
