const GET = 'GET_POST'
const GET_SUCCESS = 'GET_POST_SUCCESS'
const GET_FAILURE = 'GET_POST_FAILURE'
const SET_POST_ACTIVE = 'SET_POST_ACTIVE'
const START_SUBSCRIBE_POSTS = 'START_SUBSCRIBE_POSTS'
const SUBSRIBE_POST_IS_RUNNING = 'SUBSRIBE_POST_IS_RUNNING'
const STOP_SUBSCRIBE_POSTS = 'STOP_SUBSCRIBE_POSTS'

const postTypes = {
    GET,
    GET_SUCCESS,
    GET_FAILURE,
    SET_POST_ACTIVE,
    SUBSRIBE_POST_IS_RUNNING,
    START_SUBSCRIBE_POSTS,
    STOP_SUBSCRIBE_POSTS
}

export {
    postTypes
}
